name: sutoga deploy

on:
  push:
    branches: [ "develop" ]
  #pull_request:
    #branches: [ "deploy" ]
    #types: [closed]

jobs:
  build:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: backend/backend
      run: mvn clean install -U -DprofileIdEnabled=true -DskipTests -Dfile=sutoga.jar -DgroupId=com.sutoga -DartifactId=backend -Dversion=0.0.1 -Dpackaging=jar -DgeneratePom=true
      
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: keremmican1/sutoga
          tags: latest
          registry: docker.io
          dockerfile: backend/backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
